server:
  servlet:
    context-path: /invoice

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-1.cx1oamop9wze.eu-west-1.rds.amazonaws.com:5432/invoicedb
    username: invoice
    password: invoice!
    type: com.zaxxer.hikari.HikariDataSource
  flyway:
    url: jdbc:postgresql://database-1.cx1oamop9wze.eu-west-1.rds.amazonaws.com:5432/invoicedb
    locations: classpath:db/migrations
    user: invoice
    password: invoice!
    encoding: UTF-8
    cleanOnValidationError: true
